<a href="https://colab.research.google.com/github/berkayberatsonmez/Image_Processing/blob/main/Image_Processing_lesson_week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Python’a Giriş**

Kurulumun gerçekleştirilmesinin ardından arama
kısmına ‘Anaconda prompt (anaconda3)’ yazınız.

► Şimdi projemizi çalıştırabileceğimiz bir ortam
oluşturalım. Bu ortama ‘Environment’ denmektedir.
Bu işlem için yazacağımız kod satırı:

In [ ]:
conda create - n <enviroment_name> python=3.6.4

Kurduğumuz environment’i aktifleştirmek için gerekli
kod satırı:

In [ ]:
conda activate environment_name

Sonrasında sıklıkla kullanacağımız gerekli birkaç
kütüphaneyi ve Jupyter Notebook’u yükleyelim. Bu
işlemler için gerekli kod satırları:

In [ ]:
pip install numpy
pip install numpy
pip install jupyter notebook

Kurduğunuz Python sürümünü kontrol etmek için
gerekli kod satırı:

In [ ]:
> Python –version

https://sourceforge.net/projects/opencvlibrary/
linkinden OpenCV kurulumunu gerçekleştiriniz ve
ardından komut satırına şu kodu yazınız:


In [ ]:
conda install -c conda-forge opencv

Yüklemenin başarılı olup olmadığını kontrol etmek
için tekrar komut satırına giriyoruz ve alt kısımdaki
kodları çalıştırıyoruz:

In [ ]:
python,
import cv2
cv2.__version__

Artık jupyter notebook’u açabiliriz. Bu işlem için
Anaconda prompt ekranında ‘cd’ komutu ile gerekli
dizine ulaştıktan sonra şu komutu yazınız:

In [ ]:
Jupyter notebook

Karşımıza çıkan web sayfasında “New” butonuna
tıklayarak Python projesi oluşturmak için “Python 3”
kısmını seçelim

Karşımıza çıkan kod satırı üzerinde işlemleri
gerçekleştirebiliriz.

** Python’da Matrisler**

In [1]:
A = [[1,4,5],
    [-5,8,9]]

2x3 boyutunda A isimli matris oluşturulmuştur.

In [3]:
import numpy as np
A = np.array([[1,2,3],[3,4,5]])

İstenen boyutta, içeriği 0 veya 1 değerleri ile dolu
matrislerin oluşumunda yardımcı metotlar da
bulunmaktadır.

In [4]:
import numpy as np
array =np.zeros( (2,3) )
print(array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
import numpy as np
array =np.ones( (1,5) )
print(array)

[[1. 1. 1. 1. 1.]]


Ve diğer bazı metotlar:

In [10]:
array =np.eye(1,5)
print(array)

[[1. 0. 0. 0. 0.]]


numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)

Parameters:

N: int
    Number of rows in the output.

M: int, optional
    Number of columns in the output. If None, defaults to N.

k: int, optional
    Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal.

In [11]:
np.random.randn()

1.8355402093135653

Return a sample (or samples) from the “standard normal” distribution.

In [13]:
np.random.rand()

0.44569491780710513

Random values in a given shape.

In [16]:
a = np.matrix('1 2; 3 4')
print(a)

[[1 2]
 [3 4]]


Returns a matrix from an array-like object, or from a string of data. A matrix is a specialized 2-D array that retains its 2-D nature through operations. It has certain special operators, such as * (matrix multiplication) and ** (matrix power).

Python’da matris işlemlerini gerçekleştirmek için
kullanılabilen bazı operatörler ve metotlar:


✓ +, -, *, /, **, math.cos(), math.sin(), sqrt(), dot(), T,
transpose(), multiply(), matmul(), add(),
subtract(), divide(), shape(), linalg.inv(),
linalg.matrix_power(), size()

Python değişkenleri için kurallar:
✓Değişken adı bir harf veya alt çizgi karakteriyle başlamalıdır.
✓Değişken adı bir sayı ile başlayamaz.
✓Değişken adı yalnızca alfasayısal karakterler ve alt çizgiler
içerebilir (A-z, 0-9 ve _ ).
✓Değişken adları büyük/küçük harfe duyarlıdır (yaş, Yaş ve
AGE üç farklı değişkendir).
✓Değişken adının uzunluğu konusunda bir sınırlama yoktur

**IF Şart İfadesi**

IF ifadesinin genel biçimi şu şekildedir:

In [ ]:
if condition_1:
    statement_1
elif condition_2:
    statement_2
elif condition_3
    statement_3
    ...
else:
    statement

**FOR ifadesi**

FOR ifadesinin genel biçimi şu şekildedir:

In [ ]:
for element in sequence:
    body of for loop

**WHILE ifadesi**

WHILE ifadesinin genel biçimi şu şekildedir:

In [ ]:
while condition:
    body of while loop

**Fonksiyonlar**

► Yazdığımız bir Python uygulamasındaki belli bir kod parçasını bir kaç yerde
kullanma ihtiyacı duyduğumuzda fonksiyon oluşturmak işlerimizi kolaylaştırır.

► Böyle durumlarda sürekli kullanacak olduğumuz kod satırlarını fonksiyonlar
içine alıp istediğimiz zaman çağırıp çalıştırabiliriz.

In [29]:
def power(a,b):
    x = 1
    for i in range(b):
        x = x*a
    return x
power(2,3)    

8

verilen sayının üstünü alan fonksiyon